package ru.bz.baltic_shipyard_inventory_service.infrastructure.persistence.postgres.entity

object EntityFields {
    const val MEASURED_REMAINDER_ID = "measuredremainder_id"
    const val REMAINDER = "remainder"
    const val PROJECT = "project"
    const val MATERIAL = "material"
    const val WAREHOUSE = "warehouse"
    const val WAREHOUSE_CODE = "warehouse_code"
    const val LOCATION = "location"
    const val SEQUENCE = "sequence"
    const val STATUS = "status"
    const val COMMENT = "comment"
    const val LENGTH = "length"
    const val WIDTH = "width"
    const val DEPTH = "depth"
    const val LOCATION_SOURCE = "location_source"
    const val LOCATION_TARGET = "location_target"
    const val ITEM = "item"
    const val ITEM_CODE = "item_code"
    const val LOT = "lot"
    const val LOT_CODE = "lot_code"
    const val QUANTITY = "quantity"
    const val USER_LOGIN = "user_login"
    const val ABORT_REASON = "abort_reason"
    const val ABORT_REASON_ID = "abortreason_id"
    const val TRANSACTION_ID = "transaction_id"
    const val ERRORS = "errors"
    const val GENERAL = "general"
    const val CONTAINER_CODE = "container_code"
    const val BIN_CODE = "bin_code"
    const val BIN_CODE_TARGET = "bin_code_target"
    const val BIN_CODE_SOURCE = "bin_code_source"
}